version: "3"
services:
  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynet
  db:
    image:
      "postgres:16-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=guidepro
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - mynet

networks:
  mynet:
    driver:
      bridge